apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-prod
  labels:
    app: nginx-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-prod
  template:
    metadata:
      labels:
        app: nginx-prod
    spec:   # 👈 This will send pods only to nodes labeled 'env=prod'
      containers:
      - name: nginx
        image: nginx:1.25
        ports:
        - containerPort: 80
