apiVersion: v1
kind: Service
metadata:
  name: nginx-prod-service
  labels:
    app: nginx-prod
spec:
  selector:
    app: nginx-prod         # 👈 must match your Deployment's pod label
  ports:
    - protocol: TCP
      port: 80              # Port inside the cluster
      targetPort: 80
      nodePort: 30001
  type: NodePort          
